name: Deploy Test Env 🚀

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Build 🏭
      run: |
        npm install
        npm run build:prod
        cp README.md dist && cp -r doc dist
        sed -i "s/example/schoolWeb/"
        sed -i "s/eventotest.api/eventoapp-test.erz.be.ch/" dist/settings.example.js > dist/settings.js
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: dist 
          target-folder: test
