name: Merge Branched with ff-only

on:
  workflow_dispatch:
    inputs:
      sourceBranch:
        description: ""
        required: true
        default: "main-ci"
        type: choice
        options:
          - main-ci
          - test-ci
      targetBranch:
        description: ""
        required: true
        default: "main-ci"
        type: choice
        options:
          - test-ci
          - production-ci

jobs:
  merge-branches-with-ff-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: merge branches
        run: |
          git fetch
          git checkout ${{ inputs.targetBranch }}
          git merge --ff-only ${{ inputs.sourceBranch }}
          git log -n 1 --tags
          git push
