name: Build & Deployment Docker🚀

on:
  push:
    branches: [test-ci]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build 🏭
        run: |
          npm run build
          mv dist evento-portal
          mkdir dist
          mv evento-portal dist

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=test-ci
            type=semver,pattern={{version}},value=v1.0.0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags:
            ${{ steps.meta.outputs.tags }}

            #      - name: Deploy 🚀
            #        uses: JamesIves/github-pages-deploy-action@v4
            #        with:
            #          folder: dist
