name: Build & Deploy ZIP 📦

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build and create ZIP 🏭
        run: |
          npm run build
          mv dist evento-portal
          mkdir dist
          mv evento-portal dist
          cd dist && zip --recurse-paths evento-portal.zip *
          rm -rf evento-portal

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
